HW05. Громов Павел
PaGr0m/fl_2020_ifmo_spr pull request #5
Opened 2020-03-23 14:19 UTC by PaGr0m

2020-03-23 14:20 UTC, PaGr0m commented
Метод `parseOp` немного переделал. То есть он существует чтобы просто парсить строку, а для `parseExpr` использовал `parseOp1`, `parseOp2`и `parseOpCompare`. Это вообще легально?) Или придется переделывать?

2020-03-23 15:05 UTC, kajigor commented
> Метод `parseOp` немного переделал. То есть он существует, чтобы просто парсить строку (в тестах), а для `parseExpr` использовал `parseOp1`, `parseOp2`и `parseOpCompare`. Это вообще легально?) Или придется переделывать?

Легально, не надо переделывать. Парсеры ок. 
Не вижу спецификации -- это потому, что ее нет?

2020-03-23 15:07 UTC, PaGr0m commented
> > Метод `parseOp` немного переделал. То есть он существует, чтобы просто парсить строку (в тестах), а для `parseExpr` использовал `parseOp1`, `parseOp2`и `parseOpCompare`. Это вообще легально?) Или придется переделывать?
> 
> Легально, не надо переделывать. Парсеры ок.
> Не вижу спецификации -- это потому, что ее нет?

Скоро будет, дописываю)

2020-03-23 15:17 UTC, kajigor requested changes

2020-03-23 15:17 UTC, kajigor commented on hw/Language.md
> +COMPUTATION ::= ASSIGNMENT_LIST | IF | WHILE
То есть в программе не может быть больше одного if-выражения?

2020-03-23 15:17 UTC, kajigor commented on hw/Language.md
> +VARIABLE_DECLARATION ::= "Var" VARIABLE_LIST
А во что в абстрактном синтаксисе вы планируете транслировать объявления переменных?

2020-03-23 15:17 UTC, kajigor commented on hw/Language.md
> +FOR ::= "for" '(' EXPRESSION ')' '{' COMPUTATION '}'
Во что это будет парситься?

2020-03-23 15:17 UTC, kajigor commented on hw/Language.md
> +IF ::= "if" '(' EXPRESSION ')' '{' COMPUTATION '}'
А тут выжила ветка then или ветка else?

2020-03-23 15:17 UTC, kajigor commented on hw/Language.md
> +
Не хватает информации о пробельных символах

2020-03-24 09:59 UTC, kajigor commented
ok

2020-03-24 09:59 UTC, closed without merging