HW06. Громов Павел
PaGr0m/fl_2020_ifmo_spr pull request #6
Opened 2020-04-06 20:46 UTC by PaGr0m

С парсером своего языка проблема вышла... не могу понять почему при каждом парсе получается ошибка... И кажется, что выбрал сложную спецификацию :D 

А с UberExpr несколько тестов не проходит (они закоментированны в файле с тестами)
:c

2020-04-13 09:20 UTC, kajigor commented
Выражения у вас не парсятся потому, что вы туда парсер целого числа передаете, не положительного. Так как у нас уже есть честный унарный минус, не нужно парсить минусы как куски чисел.

2020-04-13 09:21 UTC, kajigor commented
Почему у вас в языке нет `read` и `write`?

2020-04-13 09:30 UTC, kajigor commented
Нельзя без особой на то причины менять `LAst`. Ваши конструкции можно выразить через имеющийся абстрактный синтаксис.

2020-04-13 09:35 UTC, kajigor requested changes

2020-04-13 09:35 UTC, kajigor commented on src/LLang.hs
> +parseBranching = parseIf <|> parseElseIf <|> parseElse
А вот тут пример причины, почему у вас ничего не парсится. 
`parseIf` парсит только кусок иф-выражения: только ветку `then`: 

```
λ> runParser parseIf "if (x) {x = 13;} else { x = 42; }"
Success " else { x = 42; }" (If {cond = 
x, thn = Assign {var = "x", expr = 
13}})
```

`parseElse` -- только кусок, начиная с `else`: 

```
λ> runParser parseElse "else { x = 42; }"
Success "" (Else {thn = Assign {var = "x", expr = 
42}})
```

Что-то мне подсказывает, что когда вы писали `parseBranching`, вы хотели, чтобы там прарсились иф-выражения с опциональной веткой `else` (`if (...) {...} else {...}` и `if (...) {...}`), а не только кусок с веткой `then` (`if (...) {...}`) и отдельно кусок с веткой `else` (`else {...}`). 

Если взять эти два парсера и связать друг с другом, получается примерно ожидаемое поведение (по модулю пробела и возвращаемого значения): 
```
λ> runParser (parseIf *> parseElse) "if (x) {x = 13;}else {x = 42;}"
Success "" (Else {thn = Assign {var = "x", expr = 
42}})
λ> runParser (parseIf *> parseElse) "if (x) {x = 13;} else {x = 42;}"
Failure "Predicate failed"
```

2020-04-19 18:26 UTC, PaGr0m commented
Поправил `LLang`, исправил `parseNum`

2020-05-02 10:18 UTC, kajigor commented
Так, ну язык L же не парсится все еще. 

У `If` в абстрактном синтаксисе есть обязательные ветки `thn` и `els`.  

Выражения ок.

2020-05-02 10:18 UTC, closed without merging